apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cleanup-old-pods-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: cleanup-old-pods-sa
  namespace: default
roleRef:
  kind: Role
  name: cleanup-old-pods-role
  apiGroup: rbac.authorization.k8s.io